// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ0l0GAFSOTaIu7HanIrP1Sz6_3XyfNiI',
    appId: '1:838014333470:web:f779947b23d9b9669f740f',
    messagingSenderId: '838014333470',
    projectId: 'projecteiei-e5681',
    authDomain: 'projecteiei-e5681.firebaseapp.com',
    storageBucket: 'projecteiei-e5681.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqbI__q4o5fjVfpKpHPBbqHSNQbRAY5WQ',
    appId: '1:838014333470:android:dd22db3070d8a78d9f740f',
    messagingSenderId: '838014333470',
    projectId: 'projecteiei-e5681',
    storageBucket: 'projecteiei-e5681.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClBdhFSLCBl1cUp7SHXvjAUxFRDzYrd2I',
    appId: '1:838014333470:ios:b043854fac1190329f740f',
    messagingSenderId: '838014333470',
    projectId: 'projecteiei-e5681',
    storageBucket: 'projecteiei-e5681.appspot.com',
    iosClientId: '838014333470-ptem8o2qti5fo86nh2rnpks9rbgu4kr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClBdhFSLCBl1cUp7SHXvjAUxFRDzYrd2I',
    appId: '1:838014333470:ios:b043854fac1190329f740f',
    messagingSenderId: '838014333470',
    projectId: 'projecteiei-e5681',
    storageBucket: 'projecteiei-e5681.appspot.com',
    iosClientId: '838014333470-ptem8o2qti5fo86nh2rnpks9rbgu4kr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
